// <auto-generated />
namespace THH.DAL.Migrations.ReportContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addCompany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCompany));
        
        string IMigrationMetadata.Id
        {
            get { return "201905110344420_addCompany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
