// <auto-generated />
namespace THH.DAL.Migrations.ErpContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initErp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initErp));
        
        string IMigrationMetadata.Id
        {
            get { return "201905100847414_initErp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
